const FACE_DATA = {

  oval: {
    name: 'Oval',
    emoji: '🥚',
    tagline: 'face length greater than width, balanced proportions',
    heroGradient: 'linear-gradient(135deg, #FFF0F5 0%, #F2C4C4 40%, #D97B7B 100%)',
    textColor: '#2B1A1A',
    badgeBg: '#F2C4C4',
    badgeColor: '#2B1A1A',
    oneWordSum: 'Versatile & Balanced',
    characteristics: [
      { icon: '📐', text: 'Your face length is greater than the width of your cheekbones' },
      { icon: '📏', text: 'Your forehead is slightly wider than your jawline' },
      { icon: '🔍', text: 'Your jawline is gently rounded, not sharp or angular' },
      { icon: '📊', text: 'Your proportions are naturally balanced — the most versatile face shape' },
    ],
    stylingTip: 'Lucky you — almost any hairstyle works beautifully with an oval face. You can play with different lengths, textures, and cuts freely. The main thing to avoid is covering too much of your face with heavy bangs, which can hide your naturally balanced proportions.',
    cuts: [
      { name: 'Long Layers', description: 'Add movement and texture, enhancing the natural symmetry of your face.' },
      { name: 'Blunt Bob / Lob', description: 'A sleek shoulder-length style that highlights your natural balance.' },
      { name: 'Soft Waves', description: 'Loose waves complement your balanced proportions and add playful volume.' },
      { name: 'Pixie Cut', description: 'Your balanced proportions can carry off short cuts that others can\'t.' },
    ],
    bangs: [
      { name: 'Curtain Bangs', description: 'Soft, parted bangs frame your face beautifully without hiding it.' },
      { name: 'Side-Swept Bangs', description: 'Adds dimension without disrupting your naturally balanced look.' },
    ],
    lengths: [
      { name: 'Any Length Works', description: 'From a cropped pixie to long flowing waves — your face shape handles all lengths with ease.' },
      { name: 'Avoid Heavy Full Fringe', description: 'The one thing to skip: thick, heavy bangs covering your whole forehead, which can hide your balanced proportions.' },
    ],
    styling: [
      { name: 'Voluminous Curls', description: 'Bouncy curls enhance your symmetry and add playful movement.' },
      { name: 'Sleek and Straight', description: 'Straight styles showcase your even proportions beautifully.' },
      { name: 'Half-Up Half-Down', description: 'Shows off your face shape and works for any occasion.' },
    ],
    avoid: [
      'Overly heavy, full-coverage bangs that hide your forehead entirely',
      'Styles so voluminous they make your face appear wider than it is long',
    ],
    bestCombos: [
      'Long layers + soft waves — the effortless, go-anywhere oval look',
      'Blunt lob + curtain bangs — polished and face-framing',
      'Pixie cut + side part — bold and chic',
      'Beachy waves at any length — always flattering',
    ],
  },

  round: {
    name: 'Round',
    emoji: '🔵',
    tagline: 'face nearly as wide as it is long, soft curves',
    heroGradient: 'linear-gradient(135deg, #E3F2FD 0%, #90CAF9 40%, #42A5F5 100%)',
    textColor: '#0D47A1',
    badgeBg: '#90CAF9',
    badgeColor: '#0D47A1',
    oneWordSum: 'Soft & Circular',
    characteristics: [
      { icon: '📐', text: 'Your cheekbones and face length have a similar measurement' },
      { icon: '📏', text: 'Your forehead and jawline are also similar in size' },
      { icon: '🔍', text: 'Your jawline is soft and rounded with no sharp angles' },
      { icon: '📊', text: 'Your face is nearly as wide as it is long, creating a circular appearance' },
    ],
    stylingTip: 'The goal is to add angles and the illusion of length. Angular cuts, height at the crown, and styles with vertical movement elongate your face and create a more balanced look. Avoid styles that add width at the sides, which emphasize the roundness.',
    cuts: [
      { name: 'Long Layers', description: 'Elongates the face by drawing the eye downward, breaking the roundness.' },
      { name: 'Angular Bob', description: 'Longer in the front and shorter in the back — creates angles and dimension.' },
      { name: 'Pixie with Volume at Crown', description: 'Adds height and definition to enhance your features.' },
      { name: 'Asymmetrical Bob', description: 'The uneven line adds angles and sophistication to a round face.' },
    ],
    bangs: [
      { name: 'Side-Swept Bangs', description: 'Angled bangs break up the roundness and create a chic, slimming effect.' },
      { name: 'Wispy Side Part', description: 'A deep side part adds angles and gives the illusion of a longer face.' },
    ],
    lengths: [
      { name: 'Long Styles (Past Shoulder)', description: 'Length elongates your face — the longer, the more slimming the effect.' },
      { name: 'Avoid Chin-Length Cuts', description: 'Cuts that end exactly at the chin emphasize the widest part of a round face.' },
    ],
    styling: [
      { name: 'High Ponytail', description: 'Creates the illusion of a longer face and draws the eye upward.' },
      { name: 'Straight and Sleek', description: 'Vertical lines of straight hair elongate the face naturally.' },
      { name: 'Volume at the Crown', description: 'Height on top makes the face appear longer and more oval.' },
    ],
    avoid: [
      'Blunt bobs that end at the chin — they emphasize roundness',
      'Styles with lots of volume at the sides, which widen the face',
      'Very short, uniform cuts with no height or angles',
      'Center parts with flat, lifeless hair on both sides',
    ],
    bestCombos: [
      'Long layers + side-swept bangs — slimming and elegant',
      'Angular lob + deep side part — adds angles instantly',
      'High ponytail + face-framing pieces — elongating and chic',
      'Pixie cut + volume at the crown — bold and face-lengthening',
    ],
  },

  square: {
    name: 'Square',
    emoji: '🟦',
    tagline: 'strong jawline, forehead and jaw similar width',
    heroGradient: 'linear-gradient(135deg, #E8F5E9 0%, #A5D6A7 40%, #66BB6A 100%)',
    textColor: '#1B5E20',
    badgeBg: '#A5D6A7',
    badgeColor: '#1B5E20',
    oneWordSum: 'Strong & Angular',
    characteristics: [
      { icon: '📐', text: 'Your forehead, cheekbones, and jawline are all roughly the same width' },
      { icon: '📏', text: 'Your jawline is strong, sharp, and angular' },
      { icon: '🔍', text: 'You have a broad, defined jaw that gives your face a powerful structure' },
      { icon: '📊', text: 'Your face appears nearly as wide as it is long with strong, defined edges' },
    ],
    stylingTip: 'The goal is to soften your strong jawline while adding length. Curls, waves, and layered styles break up the angular lines and create a more balanced look. Side-swept styles and layers around the face are especially flattering. Avoid blunt cuts that accentuate the jaw.',
    cuts: [
      { name: 'Textured Layers', description: 'Soften the strong angles of your jaw and add a balanced, feminine appearance.' },
      { name: 'Long Shaggy Cut', description: 'Lots of layers add movement and softness to angular features.' },
      { name: 'Soft Lob with Waves', description: 'Shoulder-length with movement breaks up the jaw\'s strong lines.' },
      { name: 'Side-Parted Long Layers', description: 'Adds dimension and draws the eye away from the jaw angle.' },
    ],
    bangs: [
      { name: 'Long Side-Swept Bangs', description: 'Soften the forehead and draw attention away from the angular jawline.' },
      { name: 'Wispy Fringe', description: 'Light, airy bangs round out the sharp edges for a more balanced look.' },
    ],
    lengths: [
      { name: 'Medium to Long', description: 'Length past the chin softens the jaw and creates a more oval appearance.' },
      { name: 'Avoid Jaw-Length Blunt Cuts', description: 'Cuts that end exactly at the jawline draw attention directly to its squareness.' },
    ],
    styling: [
      { name: 'Soft Curls or Waves', description: 'The curved lines of curls contrast beautifully with a square jaw.' },
      { name: 'Smoothing Serum + Blow-Dry', description: 'Soft, polished volume through the length softens angular features.' },
      { name: 'Loose Half-Updo', description: 'Keeps volume around the face while softening the jawline.' },
    ],
    avoid: [
      'Blunt bobs or cuts that end at the jaw — they emphasize squareness',
      'Styles with no movement or texture (sleek, flat, and straight)',
      'Very short cuts with little to no layering',
      'Center parts with equal volume on both sides that mirror the jaw width',
    ],
    bestCombos: [
      'Long waves + side-swept bangs — softens everything',
      'Textured lob + wispy fringe — modern and face-flattering',
      'Shaggy layers + off-center part — adds dimension',
      'Soft curls + smoothing serum — polished and refined',
    ],
  },

  heart: {
    name: 'Heart',
    emoji: '🫀',
    tagline: 'wider forehead tapering to a narrow pointed chin',
    heroGradient: 'linear-gradient(135deg, #FFF8E1 0%, #FFE082 40%, #FFB300 100%)',
    textColor: '#3E2723',
    badgeBg: '#FFE082',
    badgeColor: '#3E2723',
    oneWordSum: 'Wide Brow, Pointed Chin',
    characteristics: [
      { icon: '📐', text: 'Your forehead is the widest part of your face' },
      { icon: '📏', text: 'Your cheekbones are slightly narrower than your forehead' },
      { icon: '🔍', text: 'Your chin is pointed and narrow' },
      { icon: '📊', text: 'Your face tapers from a broad forehead down to a delicate pointed chin' },
    ],
    stylingTip: 'Balance a wider forehead by adding fullness at the jawline and chin. Face-framing cuts and volume through the lower half of your hair create a harmonious look. Side parts and chin-length styles are especially effective. Avoid styles with too much volume on top.',
    cuts: [
      { name: 'Layered Bob', description: 'Adds volume around the chin and jawline, perfectly complementing a heart-shaped face.' },
      { name: 'Chin-Length Bob', description: 'Draws attention to the chin area and balances the wider forehead.' },
      { name: 'Long Layers Below the Chin', description: 'Volume below the chin elongates and balances your proportions.' },
      { name: 'Wavy Lob', description: 'The lob length with waves adds fullness exactly where you need it.' },
    ],
    bangs: [
      { name: 'Side-Swept Bangs', description: 'Softens the forehead and breaks up its width for a more balanced look.' },
      { name: 'Curtain Bangs', description: 'Parts in the middle and sweeps to the sides, narrowing the appearance of the forehead.' },
    ],
    lengths: [
      { name: 'Chin-Length and Below', description: 'Adds visual width at the jawline — exactly what a heart face needs.' },
      { name: 'Avoid Very Short Cuts', description: 'Short cuts with no length at the chin can make the forehead appear even wider.' },
    ],
    styling: [
      { name: 'Voluminous Waves', description: 'Bouncy waves bring body to the lower half, balancing out a broader forehead.' },
      { name: 'Flipped Ends', description: 'Lightly flipped-out ends add width at the jawline for a soft, flattering finish.' },
      { name: 'Low, Loose Bun', description: 'Keeps volume at the lower half of the face while looking effortlessly chic.' },
    ],
    avoid: [
      'Styles with lots of volume on top or at the crown — widens an already wide forehead',
      'Very short pixie cuts with no chin-level length',
      'Center parts with flat, straight hair (no volume at the jaw)',
      'Updos that expose the full forehead without any softening fringe',
    ],
    bestCombos: [
      'Layered bob + side-swept bangs — the classic heart-face combination',
      'Wavy lob + curtain bangs — soft and balancing',
      'Long layers + flipped ends — volume exactly where you need it',
      'Chin-length bob + voluminous waves — beautiful jawline definition',
    ],
  },

  diamond: {
    name: 'Diamond',
    emoji: '💎',
    tagline: 'wide cheekbones, narrow forehead and chin',
    heroGradient: 'linear-gradient(135deg, #F3E5F5 0%, #CE93D8 40%, #AB47BC 100%)',
    textColor: '#1A0027',
    badgeBg: '#CE93D8',
    badgeColor: '#1A0027',
    oneWordSum: 'High Cheekbones & Angular',
    characteristics: [
      { icon: '📐', text: 'Your cheekbones are the widest part of your face' },
      { icon: '📏', text: 'Your forehead is narrow — narrower than your cheekbones' },
      { icon: '🔍', text: 'Your chin is pointed and narrow' },
      { icon: '📊', text: 'Your face length is the greatest measurement — narrowing at both the top and bottom' },
    ],
    stylingTip: 'The goal is to soften your striking cheekbones and add width at the forehead and jawline. Styles that add volume at the forehead and chin create balance. Avoid too much volume at the sides, which emphasizes the cheekbones further.',
    cuts: [
      { name: 'Textured Lob', description: 'Shoulder-length with texture adds width at the jawline and softens cheekbones.' },
      { name: 'Long Layers with Volume at Top', description: 'Height at the crown adds width to the narrow forehead.' },
      { name: 'Curly or Wavy Bob', description: 'Widens the jawline area and gently highlights your cheekbones.' },
      { name: 'Shoulder-Length with Layers', description: 'Frames the face and creates a balanced silhouette.' },
    ],
    bangs: [
      { name: 'Wispy Bangs', description: 'Soft, airy bangs add width to the forehead and create a more balanced shape.' },
      { name: 'Side-Swept Bangs', description: 'Reduces the appearance of a longer forehead and broadens the brow area.' },
    ],
    lengths: [
      { name: 'Medium Lengths (Chin to Shoulder)', description: 'Adds width at the jaw and chin — exactly where a diamond face needs it.' },
      { name: 'Avoid Very Short Above the Ear', description: 'Exposes the full angular structure and can emphasize the narrow forehead and jaw.' },
    ],
    styling: [
      { name: 'Beachy Waves', description: 'Tousled waves add fullness and soften angular, prominent cheekbones.' },
      { name: 'Soft Curls', description: 'Loose curls add width and movement for a more balanced look.' },
      { name: 'Volume at the Roots', description: 'Blow-drying with lift at the crown adds width to the narrow forehead.' },
    ],
    avoid: [
      'Too much volume at the sides — further emphasizes wide cheekbones',
      'Sleek, flat styles with no texture (maximizes the diamond angle)',
      'Very short cuts that expose the narrow forehead and jaw simultaneously',
      'Center parts with no bangs and flat, straight hair',
    ],
    bestCombos: [
      'Beachy waves + wispy bangs — softens and balances everything',
      'Textured lob + side-swept bangs — chic and face-flattering',
      'Curly bob + volume at sides — adds width at the jaw',
      'Long layers + volume at crown + soft curls — elegant and balanced',
    ],
  },

  rectangle: {
    name: 'Rectangle',
    emoji: '▬',
    tagline: 'face length greatest, forehead and jaw similar width',
    heroGradient: 'linear-gradient(135deg, #FFF9F0 0%, #FFE8CC 40%, #FFD6B0 100%)',
    textColor: '#5C3A1E',
    badgeBg: '#FFD6B0',
    badgeColor: '#5C3A1E',
    oneWordSum: 'Long & Angular',
    characteristics: [
      { icon: '📐', text: 'Your face length is the greatest measurement' },
      { icon: '📏', text: 'Your forehead, cheekbones, and jawline are similar in width' },
      { icon: '🔍', text: 'Your jawline tends to be angular rather than rounded' },
      { icon: '📊', text: 'Your face is noticeably longer than it is wide, giving an elongated appearance' },
    ],
    stylingTip: 'Balance your longer face with volume on the sides and avoid too much height on top. Styles that add width and fullness at the sides create the illusion of a shorter, more oval face. Soft layered fringe and waves that hit at the sides are especially flattering.',
    cuts: [
      { name: 'Shoulder-Length Waves', description: 'Loose waves add width to the sides of your face and a touch of softness.' },
      { name: 'Chin-Length Bob', description: 'Helps balance the length and draws focus to your features at the right level.' },
      { name: 'Layered Cut with Side Volume', description: 'Layers that flare out at the sides create width and break up the length.' },
      { name: 'Shaggy Cut', description: 'Heavy layers and texture add width while softening the angular jaw.' },
    ],
    bangs: [
      { name: 'Soft Layered Fringe', description: 'Wispy bangs and layers round out sharper angles and shorten the face visually.' },
      { name: 'Curtain Bangs', description: 'Add width at the forehead level while shortening the apparent face length.' },
    ],
    lengths: [
      { name: 'Chin to Shoulder Length', description: 'Medium lengths add width at the face\'s widest natural points.' },
      { name: 'Avoid Very Long Straight Styles', description: 'Long, straight hair with no volume at the sides elongates a face that doesn\'t need it.' },
    ],
    styling: [
      { name: 'Side Volume Blow-Out', description: 'Blow-dry flipping outward at the sides to add the width you need.' },
      { name: 'Loose Waves', description: 'Wave patterns at the sides create natural volume and break up the length.' },
      { name: 'Low Side Bun', description: 'Keeps width at the side of the face without adding height on top.' },
    ],
    avoid: [
      'Too much height at the crown — further elongates an already long face',
      'Very long, straight hair with no side volume',
      'Sleek center parts with hair lying flat on both sides',
      'Very short cuts with no side volume or width',
    ],
    bestCombos: [
      'Shoulder-length waves + curtain bangs — adds width perfectly',
      'Chin-length bob + soft layered fringe — balanced and flattering',
      'Shaggy layers + side volume blow-out — maximum width',
      'Layered lob + loose waves — natural and softening',
    ],
  },

  triangle: {
    name: 'Triangle',
    emoji: '🔺',
    tagline: 'wider jawline, narrowing toward the forehead',
    heroGradient: 'linear-gradient(135deg, #E8F5E9 0%, #C8E6C9 40%, #A5D6A7 100%)',
    textColor: '#1B5E20',
    badgeBg: '#C8E6C9',
    badgeColor: '#1B5E20',
    oneWordSum: 'Wide Jaw, Narrow Brow',
    characteristics: [
      { icon: '📐', text: 'Your jawline is the widest part of your face' },
      { icon: '📏', text: 'Your cheekbones are wider than your forehead' },
      { icon: '🔍', text: 'Your forehead is the narrowest part, tapering upward' },
      { icon: '📊', text: 'Your face widens from the forehead down to the jaw — the opposite of a heart shape' },
    ],
    stylingTip: 'Add volume around the forehead and temples to balance a wider jawline. Layered cuts with fullness at the top draw attention upward and create balance. Avoid styles that add volume at the jaw, which will make it appear even wider.',
    cuts: [
      { name: 'Layered Cut with Volume at Crown', description: 'Volume at the top balances the wider jaw and draws the eye upward.' },
      { name: 'Long Waves with Root Volume', description: 'Fullness at the roots widens the forehead area for better balance.' },
      { name: 'Side-Parted Styles', description: 'A side part creates asymmetry that distracts from a wide jaw.' },
      { name: 'Textured Bob Above the Jaw', description: 'Ends above the widest jaw point, avoiding adding volume there.' },
    ],
    bangs: [
      { name: 'Full Fringe', description: 'Adds width across the forehead, balancing a wider jaw below.' },
      { name: 'Side-Swept Bangs', description: 'Creates asymmetry at the top of the face to draw attention upward.' },
    ],
    lengths: [
      { name: 'Long with Root Volume', description: 'Length is fine as long as there\'s volume at the roots and crown.' },
      { name: 'Avoid Volume at Jaw Level', description: 'Flipped ends or curls that end at the jaw will widen it further.' },
    ],
    styling: [
      { name: 'Volume at the Roots', description: 'Lifting the roots with a blow-dryer adds width to the narrow forehead area.' },
      { name: 'Loose Waves Starting High', description: 'Waves that begin near the crown add the volume where you need it.' },
      { name: 'High Half-Up Styles', description: 'Adds height and visual width at the forehead and crown.' },
    ],
    avoid: [
      'Styles with lots of volume or curls at jaw level',
      'Blunt cuts that end exactly at the widest part of the jaw',
      'Center parts with flat, lifeless hair — no volume at the crown',
      'Very sleek, straight styles that draw attention downward to the jaw',
    ],
    bestCombos: [
      'Long waves + full fringe — adds width at the top beautifully',
      'Layered cut + volume at crown + side part — balanced and chic',
      'Textured bob above jaw + side-swept bangs — keeps attention at the top',
      'High half-up + loose waves — draws the eye upward',
    ],
  },

};