
const SEASON_DATA = {
  // ── SPRING ──────────────────────────────────────────
  bright_spring: {
    heroGradient: 'linear-gradient(135deg, #FFF0F5 0%, #FFD6E8 40%, #FFB8D4 100%)',
    textColor: '#5C1A3A',
    badgeBg: '#FFB8D4',
    badgeColor: '#5C1A3A',
    emoji: '✨',
    oneWordSum: 'Neutral-warm',
    traits: [
      { icon: '🌈', text: 'Extremely saturated and bright colors suit you best' },
      { icon: '🔀', text: 'Flows from Winter into Spring — neutral-warm coloring' },
      { icon: '⚡', text: 'High contrast patterns work well: geometric, dotty, busy, or stylised flowers' },
      { icon: '🚫', text: 'Avoid muted or toned-down colors — they make you look muddy' },
    ],
    palette: [
    { hex: '#fe4c04' },
    { hex: '#fe7c61' },
    { hex: '#e30048' },
    { hex: '#f952a8' },
    { hex: '#8403b5' },
    { hex: '#0166b1' },
    { hex: '#0533fe' },
    { hex: '#00cfd4' },
    { hex: '#029201' },
    { hex: '#52e13a' },
    { hex: '#1f1f1f' },
    { hex: '#fde404' },
    ],
    bestCombos: [
      'Hue contrast: Pair opposite colors on the color wheel (e.g., pink and green)',
      'Neutral + Bright accent: Dark neutral with a light/bright accent, or vice versa',
      'Value contrast: Pair dark and light versions of the same hue',
      'High contrast patterns: Geometric, dotty, busy, or stylised flowers with larger elements',
    ],
    worstCombos: [
      'Neutrals-only: Lacks the vibrancy to lift your appearance',
      'Monochromatic: Too low in contrast for your natural coloring',
      'Low contrast colors: Blended or muted combinations',
    ],
    avoid: [
      { hex: '#8FBC8F', name: 'Dusty Blue' },
      { hex: '#8B7355', name: 'Muddy Brown' },
      { hex: '#ADD8E6', name: 'Icy Blue' },
      { hex: '#C0C0C0', name: 'Cool Grey' },
    ],
    avoidNote: 'Muted/toned-down and very cool colors clash with your warm undertones and make you look muddy. Avoid faded prints with small or blended elements.',
    tip: 'You are the only Spring that can handle near-Winter intensity. Always include at least one very bright, saturated color in your look.',
  },

  true_spring: {
    heroGradient: 'linear-gradient(135deg, #FFF8E1 0%, #FFE082 40%, #FFD54F 100%)',
    textColor: '#4A2C00',
    badgeBg: '#FFE082',
    badgeColor: '#4A2C00',
    emoji: '🌸',
    oneWordSum: 'Intensely warm',
    traits: [
      { icon: '☀️', text: 'Intensely warm and sunny coloring with no trace of coolness' },
      { icon: '🎨', text: 'Colors are reminiscent of coloring pencils — clear, warm, and bright' },
      { icon: '🚫', text: 'Does not tolerate cool or muted colors at all' },
      { icon: '🌿', text: 'Hair often golden, strawberry, or auburn; eyes warm blue, green, hazel, or brown' },
    ],
    palette: [
    { hex: '#f2824a' },
    { hex: '#ce3627' },
    { hex: '#a585c9' },
    { hex: '#624ba1' },
    { hex: '#00c8c8' },
    { hex: '#17a04b' },
    { hex: '#9cfe72' },
    { hex: '#53813b' },
    { hex: '#aec641' },
    { hex: '#8d4735' },
    { hex: '#f9d6a4' },
    { hex: '#f1c347' },
    ],
    bestCombos: [
      'Hue contrast: Colors far apart on the wheel (e.g., peachy orange and teal) or neighboring hues (yellow and green)',
      'Value contrast: Tints with shades of the same hue (e.g., light green with dark green)',
      'Neutral + Bright accent: Dark neutrals (chocolate brown) with lighter accents, or light neutrals with darker accents',
      'Medium-high contrast patterns: Dotty, busy, rounded geometric shapes; natural elements like flowers and birds',
    ],
    worstCombos: [
      'Neutrals-only: Looks dull and fails to lift your naturally bright appearance',
      'Monochromatic: Too low in contrast for your features',
      'Black and White: Too cool and harsh; can make skin look sallow',
    ],
    avoid: [
      { hex: '#ADD8E6', name: 'Icy Blue' },
      { hex: '#C0C0C0', name: 'Cool Grey' },
      { hex: '#8FBC8F', name: 'Dusty Blue' },
      { hex: '#4B0082', name: 'Deep Purple' },
    ],
    avoidNote: 'Very cool and muted colors make you look unhealthy or muddy. Avoid dark, harsh blues and purples, very small prints, and stiff geometric patterns.',
    tip: 'Warm, yellow gold is your best metal. Your palette is like a sunny meadow — keep it warm, clear, and joyful.',
  },

  light_spring: {
    heroGradient: 'linear-gradient(135deg, #FFF9F0 0%, #FFE8CC 40%, #FFD6B0 100%)',
    textColor: '#5C3A1E',
    badgeBg: '#FFD6B0',
    badgeColor: '#5C3A1E',
    emoji: '🍬',
    oneWordSum: 'Neutral-warm, delicate',
    traits: [
      { icon: '🍬', text: 'Palette is colorful like a "box of sweets" — lightest and least intense Spring' },
      { icon: '🌸', text: 'Neutral-warm; shares gentleness with Summer as it flows Spring into Summer' },
      { icon: '✨', text: 'Always include at least one bright color to avoid looking dull' },
      { icon: '🚫', text: 'Black and white are too harsh — avoid them entirely' },
    ],
    palette: [
    { hex: '#f97568' },
    { hex: '#f2bd98' },
    { hex: '#fd4173' },
    { hex: '#ffbecb' },
    { hex: '#555ab8' },
    { hex: '#9883bf' },
    { hex: '#309cc3' },
    { hex: '#7efdf7' },
    { hex: '#67b659' },
    { hex: '#bbdb97' },
    { hex: '#5f4733' },
    { hex: '#f6e078' },
    ],
    bestCombos: [
      'Playful color contrast: Neighboring hues (yellow and green) or opposite hues (orange and blue)',
      'Neutral + Bright accent: Pair a dark neutral with a lighter accent, or a light neutral with a darker accent',
      'Vibrant accents: Always include at least one bright color to avoid looking dull',
      'Low-contrast patterns: Delicate, busy, or dotty prints with small, dense elements (flowers, butterflies)',
    ],
    worstCombos: [
      'Neutrals-only: Looks dull and fails to lift your delicate appearance',
      'Monochromatic: Lacks the necessary vibrancy',
      'High-contrast/Bold patterns: Overwhelms your low-contrast features',
      'Black and White: Too harsh, cold, and dark; makes you look aged',
    ],
    avoid: [
      { hex: '#000000', name: 'True Black' },
      { hex: '#FFFFFF', name: 'Pure White' },
      { hex: '#FF8C00', name: 'Burnt Orange' },
      { hex: '#4B0082', name: 'Dark Purple' },
    ],
    avoidNote: 'Avoid dark and heavy colors, cool icy tones, and overly saturated colors like burnt orange or neon — you will disappear behind them. No large elements or stiff geometric prints.',
    tip: 'Gold is the most foolproof metal choice. Keep everything light, fresh, and sweet — like your coloring.',
  },

  // ── SUMMER ──────────────────────────────────────────
  light_summer: {
    heroGradient: 'linear-gradient(135deg, #F0F8FF 0%, #E0F0FF 40%, #C8E8FF 100%)',
    textColor: '#1A3A5C',
    badgeBg: '#C8E8FF',
    badgeColor: '#1A3A5C',
    emoji: '🍦',
    oneWordSum: 'Neutral-cool, delicate',
    traits: [
      { icon: '🍦', text: 'Colors are like various flavors of ice cream — soft, cool, and delicate' },
      { icon: '🫧', text: 'Neutral-cool with low contrast between features' },
      { icon: '✨', text: 'Always include at least one gentle accent color to avoid looking washed out' },
      { icon: '🚫', text: 'Black and white are too harsh — avoid them' },
    ],
    palette: [
      { hex: '#cdced1' },
      { hex: '#a1a6af' },
      { hex: '#cf92a6' },
      { hex: '#8f586b' },
      { hex: '#544f7b' },
      { hex: '#9dabd4' },
      { hex: '#667bec' },
      { hex: '#3d4b76' },
      { hex: '#a6d3ba' },
      { hex: '#678d7d' },
      { hex: '#557a7c' },
      { hex: '#f9f8be' },
    ],
    bestCombos: [
      'Playful color contrast: Neighboring hues or gentle opposites',
      'Neutral + Soft accent: Always include at least one soft bright color',
      'Low-contrast patterns: Delicate, small, and airy elements',
    ],
    worstCombos: [
      'Neutrals-only: Looks washed out',
      'High contrast or bold patterns: Overwhelms your delicate features',
      'Black and White: Too harsh and cold',
    ],
    avoid: [
      { hex: '#000000', name: 'True Black' },
      { hex: '#FFFFFF', name: 'Pure White' },
      { hex: '#FF8C00', name: 'Burnt Orange' },
      { hex: '#DAA520', name: 'Warm Gold' },
    ],
    avoidNote: 'Warm, earthy, and highly saturated colors clash with your cool delicacy. Avoid large elements or bold geometric prints.',
    tip: 'Keep your palette soft and cool, like a watercolor painting. Silver and light metals suit you best.',
  },

  true_summer: {
    heroGradient: 'linear-gradient(135deg, #E8EAF6 0%, #C5CAE9 40%, #9FA8DA 100%)',
    textColor: '#1A237E',
    badgeBg: '#9FA8DA',
    badgeColor: '#FAFAFA',
    emoji: '🌊',
    oneWordSum: 'Intensely cool',
    traits: [
      { icon: '🫧', text: 'Cool and muted — the coolest season of the Summer family' },
      { icon: '❄️', text: 'Intensely cool features that lack any trace of warmth' },
      { icon: '🚫', text: 'Does not tolerate warm or bright colors at all' },
      { icon: '👁️', text: 'Eyes often blue, grey, or soft green; hair ash blonde or ash brown' },
    ],
    palette: [
      { hex: '#a4998c' },
      { hex: '#5a5e69' },
      { hex: '#c06379' },
      { hex: '#955a81' },
      { hex: '#773a41' },
      { hex: '#737cab' },
      { hex: '#73669c' },
      { hex: '#434671' },
      { hex: '#a6d0e3' },
      { hex: '#688f7f' },
      { hex: '#394d4e' },
      { hex: '#dbcac3' },
    ],
    bestCombos: [
      'Monochromatic: Pairing a lighter tint with a darker shade of the same hue',
      'Gentle hue contrast: Combining neighboring hues of similar value (e.g., pink and lavender)',
      'Neutral + Accent: Neutrals with a brighter accent of similar or slightly different value',
      'Medium-contrast patterns: Loosely arranged watercolor textures, floral drawings, brush strokes',
    ],
    worstCombos: [
      'High-contrast hues: Colors opposite each other on the color wheel (e.g., yellow and purple)',
      'Black and White: True black ages the skin; pure white is too bright',
      'Bold/Stiff patterns: Overwhelms your naturally soft, blended appearance',
    ],
    avoid: [
      { hex: '#FFD700', name: 'Bright Yellow' },
      { hex: '#FF8C00', name: 'Orange' },
      { hex: '#000000', name: 'True Black' },
      { hex: '#FFFFFF', name: 'Pure White' },
    ],
    avoidNote: 'Warm and saturated colors with yellow undertones clash harshly. Avoid dark and harsh colors, small dense prints, and stiff geometric patterns.',
    tip: 'Silver, white gold, and platinum are your metals. Keep everything muted, cool, and softly blended.',
  },

  soft_summer: {
    heroGradient: 'linear-gradient(135deg, #ECEFF1 0%, #CFD8DC 40%, #B0BEC5 100%)',
    textColor: '#263238',
    badgeBg: '#B0BEC5',
    badgeColor: '#263238',
    emoji: '🌫️',
    oneWordSum: 'Neutral-cool, softest',
    traits: [
      { icon: '🌫️', text: 'Softest, most "greyed out" coloring of the Summer family' },
      { icon: '🍂', text: 'Neutral-cool; flows from Summer into Autumn' },
      { icon: '🚫', text: 'Does not tolerate brightness at all' },
      { icon: '🎨', text: 'All colors should be muted, toned-down, and gentle' },
    ],
    palette: [
      { hex: '#867f77' },
      { hex: '#4d4342' },
      { hex: '#dba5b8' },
      { hex: '#824852' },
      { hex: '#4a3c46' },
      { hex: '#a2bbc6' },
      { hex: '#637b8a' },
      { hex: '#547699' },
      { hex: '#9eb99c' },
      { hex: '#618c69' },
      { hex: '#3d4e3e' },
      { hex: '#ddd6a7' },
    ],
    bestCombos: [
      'Monochromatic: Slightly different shades of the same hue (e.g., light green with darker green)',
      'Low-contrast hue contrast: Neighboring hues of the same value (e.g., lavender with light blue)',
      'Tone-on-tone: Neutral with an accent of similar value (e.g., light beige with light yellow)',
      'Delicate patterns: Small, loosely arranged watercolor textures, floral drawings, feathers, or birds',
    ],
    worstCombos: [
      'Highly contrasting colors: Especially opposites on the color wheel (e.g., blue and orange)',
      'Black and White: Both are too harsh — black ages you, white is too intense',
      'Bright/Vibrant combinations: Swallows up your delicate, soft appearance',
    ],
    avoid: [
      { hex: '#FF4500', name: 'Bright Orange' },
      { hex: '#DAA520', name: 'Goldenrod' },
      { hex: '#000000', name: 'True Black' },
      { hex: '#FFFFFF', name: 'Pure White' },
    ],
    avoidNote: 'Bright and saturated colors, rich warm tones, and harsh dark/light contrasts all overwhelm your subtlety. Avoid big elements, ordered arrangements, and geometric patterns.',
    tip: 'Silver is the most flattering metal. Keep all finishes gentle — brushed, matte, or satin. Never shiny or polished.',
  },

  // ── AUTUMN ──────────────────────────────────────────
  soft_autumn: {
    heroGradient: 'linear-gradient(135deg, #F5F0E8 0%, #E8DCC8 40%, #D4C4A8 100%)',
    textColor: '#3C2C1A',
    badgeBg: '#D4C4A8',
    badgeColor: '#3C2C1A',
    emoji: '🍃',
    oneWordSum: 'Neutral-warm, softest',
    traits: [
      { icon: '🍃', text: 'Softest coloring of the Autumn family — muted and warm' },
      { icon: '🌅', text: 'Neutral-warm; no brightness at all — palette is extremely toned down' },
      { icon: '🚫', text: 'Avoid shiny or polished finishes — they overwhelm your subtle coloring' },
      { icon: '🌿', text: 'Natural materials like wood accessories and yellow stones (citrine, amber) are excellent' },
    ],
    palette: [
      { hex: '#c07f77' },
      { hex: '#6b3d40' },
      { hex: '#5d6283' },
      { hex: '#373a4f' },
      { hex: '#5e799c' },
      { hex: '#3c4d68' },
      { hex: '#62837b' },
      { hex: '#364540' },
      { hex: '#a2a486' },
      { hex: '#7b7b65' },
      { hex: '#ccb581' },
      { hex: '#65594b' },
    ],
    bestCombos: [
      'Monochromatic: Slightly different shades of the same hue (e.g., lighter green with darker green)',
      'Low-contrast hue contrast: Neighboring hues of the same value (e.g., medium blue with medium green)',
      'Tone-on-tone: Neutral with an accent of similar value (e.g., medium brown with medium red)',
      'Natural patterns: Small, loosely arranged elements like leaves, wood structures, and small florals',
    ],
    worstCombos: [
      'Highly contrasting colors: Especially opposites on the color wheel (e.g., blue and orange)',
      'Black and White: True black makes you look aged/unhealthy; true white is too harsh and cool',
      'High-contrast patterns: Bold, ordered, or large-scale prints overwhelm your blended look',
    ],
    avoid: [
      { hex: '#FF6347', name: 'Intense Orange' },
      { hex: '#4B0082', name: 'Deep Purple' },
      { hex: '#000000', name: 'True Black' },
      { hex: '#FFFFFF', name: 'Pure White' },
    ],
    avoidNote: 'Bright and saturated colors look clownish; deep purples/blues make you disappear. Avoid cool greys, black, white, geometric patterns, and large or stiff prints.',
    tip: 'All metals work if they are muted — brushed, matte, satin, hammered, or antiqued. Never shiny. Avoid most coppers as they are often too orange.',
  },

  true_autumn: {
    heroGradient: 'linear-gradient(135deg, #FFF0E0 0%, #F5DEB3 40%, #DEB887 100%)',
    textColor: '#4A2800',
    badgeBg: '#C4956A',
    badgeColor: '#FFF5E8',
    emoji: '🍂',
    oneWordSum: 'Intensely warm',
    traits: [
      { icon: '🔥', text: 'Warmest season of the Autumn family — warm and muted' },
      { icon: '🍁', text: 'Rich but not saturated; colors are earthy like autumn foliage' },
      { icon: '🌰', text: 'Hair often brown, auburn, or copper; eyes brown, hazel, olive, or amber' },
      { icon: '🚫', text: 'Avoid overly shiny metals — they clash with your muted appearance' },
    ],
    palette: [
      { hex: '#bf695a' },
      { hex: '#673e38' },
      { hex: '#696081' },
      { hex: '#453f51' },
      { hex: '#80acc0' },
      { hex: '#506f80' },
      { hex: '#71a480' },
      { hex: '#5c8279' },
      { hex: '#92a977' },
      { hex: '#566a44' },
      { hex: '#e9d566' },
      { hex: '#65603e' },
    ],
    bestCombos: [
      'Low to medium contrast: Colors resembling each other in hue or value',
      'Monochromatic: Different shades of one hue (e.g., light green with dark green)',
      'Analogous contrast: Neighboring hues with similar values (e.g., medium orange with medium pink)',
      'Neutral + Rich accent: Dark neutrals (dark brown) with lighter, richer accents (mustard yellow)',
      'Stylized patterns: Paisley, oriental patterns, wood structures, and leaf prints',
    ],
    worstCombos: [
      'Extreme contrast: Colors opposite each other on the color wheel (e.g., bright blue and orange)',
      'Black and White: True black is too harsh/cool; pure white is too cold',
      'Neutrals-only: Can look bland without a pop of rich color',
    ],
    avoid: [
      { hex: '#FF69B4', name: 'Pastel Pink' },
      { hex: '#ADD8E6', name: 'Ice Blue' },
      { hex: '#FF00FF', name: 'Neon Pink' },
      { hex: '#000000', name: 'True Black' },
    ],
    avoidNote: 'Cool and bright pastels, extremely vibrant neons, and harsh black/white all clash with your earthy warmth. Avoid very small dense arrangements and stark high-contrast elements.',
    tip: 'Gold, copper, brass, and bronze are your metals. Choose hammered, oxidized, or antiqued finishes — never overly shiny.',
  },

  dark_autumn: {
    heroGradient: 'linear-gradient(135deg, #3D2B1F 0%, #6B4226 40%, #8B5E3C 100%)',
    textColor: '#F5E6D0',
    badgeBg: '#8B5E3C',
    badgeColor: '#F5E6D0',
    emoji: '🌶️',
    oneWordSum: 'Neutral-warm, deep',
    traits: [
      { icon: '🌶️', text: 'Deep, spicy colors with higher contrast than other Autumns' },
      { icon: '🍂', text: 'Neutral-warm; flows from Autumn into Winter' },
      { icon: '⚡', text: 'Higher contrast than other Autumns — value contrast is your primary tool' },
      { icon: '🚫', text: 'Light and cool pastels will wash you out entirely' },
    ],
    palette: [
      { hex: '#d58d83' },
      { hex: '#99403a' },
      { hex: '#a67187' },
      { hex: '#542c41' },
      { hex: '#8cb2c5' },
      { hex: '#333a51' },
      { hex: '#6f9994' },
      { hex: '#222c31' },
      { hex: '#afb77b' },
      { hex: '#616547' },
      { hex: '#ddbe84' },
      { hex: '#875c3e' },
    ],
    bestCombos: [
      'Value contrast: Pairing very light colors with very dark colors — the primary way to create contrast',
      'Dark Neutral + Bright accent: Dark chocolate or warm black with lighter, richer accent colors',
      'Hue contrast: Pairing opposites on the color wheel (e.g., yellow and blue) for maximum impact',
      'Bold patterns: Highly stylized natural forms, paisley, and oriental patterns with big, loosely arranged elements',
    ],
    worstCombos: [
      'Monochromatic: Looks dull unless you combine the absolute lightest and darkest shades',
      'Neutrals-only: Often appears bland and fails to complement your rich coloring',
      'Low contrast: Tepid combinations that do not reflect your natural high contrast',
    ],
    avoid: [
      { hex: '#FFFFFF', name: 'Pure White' },
      { hex: '#FFB6C1', name: 'Pastel Pink' },
      { hex: '#ADD8E6', name: 'Dusty Blue' },
      { hex: '#E6E6FA', name: 'Lavender' },
    ],
    avoidNote: 'Pure white, pastels, dusty blues/pinks, and frosty cool tones make you look washed out. Avoid small dense patterns and stiff square geometric prints.',
    tip: 'Bronze, brass, gold, copper, and pewter are your metals. Use true black as an accent rather than an all-black look to avoid being diminished.',
  },

  // ── WINTER ──────────────────────────────────────────
  dark_winter: {
    heroGradient: 'linear-gradient(135deg, #1A1A2E 0%, #2D2D4A 40%, #3D3D6B 100%)',
    textColor: '#E8E8FF',
    badgeBg: '#3D3D6B',
    badgeColor: '#E8E8FF',
    emoji: '🌑',
    oneWordSum: 'Neutral-cool, darkest',
    traits: [
      { icon: '🌑', text: 'Darkest coloring of the Winter family — flows from Autumn into Winter' },
      { icon: '💎', text: 'Neutral-cool with high value contrast between very light and very dark' },
      { icon: '⚡', text: 'Always aim for a mixture of light and dark values to replicate your natural intensity' },
      { icon: '🚫', text: 'Warm and earthy tones make you look unhealthy' },
    ],
    palette: [
      { hex: '#a24857' },
      { hex: '#6843a1' },
      { hex: '#8c76b0' },
      { hex: '#272e74' },
      { hex: '#648bd4' },
      { hex: '#374a58' },
      { hex: '#5f8b57' },
      { hex: '#405647' },
      { hex: '#d4d869' },
      { hex: '#332b29' },
      { hex: '#c095bb' },
      { hex: '#642a2d' },
    ],
    bestCombos: [
      'Value Contrast + Hue Contrast: Light neutral in one hue with a dark accent in another (e.g., light grey with dark purple)',
      'Dark Neutral + Bright Accent: Dark green with bright pink',
      'High Contrast: Always mix light and dark values to replicate your natural intensity',
      'Bold Patterns: Highly contrasted, geometric, or abstract prints with unusual/unexpected elements',
    ],
    worstCombos: [
      'All-Light look: Fails to support your naturally dark value',
      'Monochromatic/Neutrals-only: Looks dull and washes out your high-contrast features',
      'Blended/Faded: Avoid watercolors or patterns where colors bleed into each other',
    ],
    avoid: [
      { hex: '#DAA520', name: 'Golden Orange' },
      { hex: '#D2B48C', name: 'Warm Tan' },
      { hex: '#F5DEB3', name: 'Wheat' },
      { hex: '#BC8F5F', name: 'Warm Pastel' },
    ],
    avoidNote: 'Warm and earthy tones, warm pastels, and desaturated "muddy" colors all make you look unhealthy. Avoid small dense arrangements and stiff square geometric patterns.',
    tip: 'Silver and pewter are your best metals. Dark gold can work if it is not too yellow. Sapphire, ruby, emerald, and saturated violet stones are your best choices.',
  },

  true_winter: {
    heroGradient: 'linear-gradient(135deg, #E8E8F0 0%, #D0D0E8 40%, #B8B8D8 100%)',
    textColor: '#0A0A2A',
    badgeBg: '#3A3A5C',
    badgeColor: '#E8E8FF',
    emoji: '❄️',
    oneWordSum: 'Intensely cool',
    traits: [
      { icon: '❄️', text: 'Coolest season of the Winter family — features overlaid with frost-like coolness' },
      { icon: '⚡', text: 'High contrast between skin, hair, and eyes' },
      { icon: '🖤', text: 'The only season that truly pulls off Black and White as a combination' },
      { icon: '🚫', text: 'Warm and earthy tones clash completely with your coolness' },
    ],
    palette: [
      { hex: '#a24958' },
      { hex: '#c87499' },
      { hex: '#874664' },
      { hex: '#7e629b' },
      { hex: '#4c4583' },
      { hex: '#6784c8' },
      { hex: '#3a4796' },
      { hex: '#9ac8a3' },
      { hex: '#547465' },
      { hex: '#f0e185' },
      { hex: '#444444' },
      { hex: '#dedfe3' },
    ],
    bestCombos: [
      'Black and White: The classic True Winter combination — you are the only season that truly pulls this off',
      'High Value Contrast: Dark neutrals paired with lighter or brighter accents (e.g., dark blue with bright blue)',
      'Neutral + Accent: Always aim for at least one neutral paired with a pop of color',
      'Bold Patterns: High-contrast, geometric, or abstract prints; black and white or neon-colored patterns',
    ],
    worstCombos: [
      'Extreme Color Contrast: Pairing opposites (yellow and purple) can be overpowering — stick to neutral + accent',
      'Monochromatic: Contrast is always superior to all-dark or all-light looks',
      'Blended/Faded: Avoid watercolor prints or anything where colors bleed together',
    ],
    avoid: [
      { hex: '#F4A460', name: 'Warm Tan' },
      { hex: '#DEB887', name: 'Burlywood' },
      { hex: '#F5DEB3', name: 'Wheat' },
      { hex: '#DAA520', name: 'Goldenrod' },
    ],
    avoidNote: 'Warm and earthy tones, soft and muted colors, warm pastels, and muted neutrals all dull your natural drama. Avoid small dense prints and anything faded or blended.',
    tip: 'Silver and platinum are your metals — always polished and shiny. Diamonds, rubies, and sapphires are ideal stones. Use highly stylized (not realistic) floral prints.',
  },

  bright_winter: {
    heroGradient: 'linear-gradient(135deg, #F0F0FF 0%, #D8D8FF 40%, #B8B8FF 100%)',
    textColor: '#0A0A4A',
    badgeBg: '#B8B8FF',
    badgeColor: '#0A0A4A',
    emoji: '💫',
    oneWordSum: 'Neutral-cool, brilliant',
    traits: [
      { icon: '💫', text: 'Neutral-cool with striking brilliance and vibrance — flows from Winter into Spring' },
      { icon: '🌈', text: 'Colors are extremely bright and saturated' },
      { icon: '⚡', text: 'Even black and white together might not be enough — always add at least one bright color' },
      { icon: '🚫', text: 'Muted and toned-down colors drain all life from your appearance' },
    ],
    palette: [
      { hex: '#ce77a4' },
      { hex: '#a4446e' },
      { hex: '#ac76d7' },
      { hex: '#60327b' },
      { hex: '#8fbfdf' },
      { hex: '#3942c4' },
      { hex: '#89c08d' },
      { hex: '#5a834d' },
      { hex: '#b3ce5f' },
      { hex: '#060822' },
      { hex: '#f0ec8d' },
      { hex: '#c94f57' },
    ],
    bestCombos: [
      'Hue Contrast: Pair opposite colors (e.g., hot pink and teal) — unusual, wild combinations look striking on you',
      'High Value Contrast: Dark or light neutrals with "acid" or neon accents (e.g., black with lemon yellow)',
      'The "Lift": Always add at least one bright, saturated color to your outfit',
      'Bold Patterns: Highly contrasted, geometric, or abstract prints; neon-colored patterns are excellent',
    ],
    worstCombos: [
      'Monochromatic: All-one-color looks will diminish your vibrant natural coloring',
      'Low Contrast: Any combination that blends together or lacks intensity looks very dull',
      'Toned-down Neutrals: Never wear only black, only white, or only grey without a bright accent',
    ],
    avoid: [
      { hex: '#C4956A', name: 'Orangey Brown' },
      { hex: '#DAA520', name: 'Golden Yellow' },
      { hex: '#B7410E', name: 'Rusty Orange' },
      { hex: '#C4A882', name: 'Muted Beige' },
    ],
    avoidNote: 'Warm and earthy tones, muted and toned-down colors, pale gold, and dusty earth tones make you look drained or yellow. Avoid small dense prints and anything faded or blended.',
    tip: 'Silver and platinum are best — always shiny and polished. White gold and light gold work if very bright and shiny. Sapphires are your ideal stone.',
  },
};